spring:
  application:
    name: java-spring-boot-arquitetura-hexagonal
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: example
      database: hexagonal

config:
  client:
    address:
      url: http://localhost:8082/addresses

