spring:
  application:
    name: java-spring-boot-arquitetura-hexagonal
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: s3nhaCompl3xa
      database: java_spring_boot_arquitetura_hexagonal

config:
  client:
    address:
      url: http://localhost:8082/addresses

